#!/bin/zsh

STATE_FILE="$HOME/.config/hypr/scripts/.kb_state"

KB_STATE=$(cat "$STATE_FILE")

if [ "$1" = "next" ]; then
    if [ "$KB_STATE" -ne 3 ]; then  
	KB_STATE=$((KB_STATE + 1))  
        asusctl --next-kbd-bright  
    fi
elif [ "$1" = "prev" ]; then
    if [ "$KB_STATE" -ne 0 ]; then  
        KB_STATE=$((KB_STATE - 1))  
        asusctl --prev-kbd-bright 
    fi
elif [ "$1" = "boot" ]; then
    asusctl --kbd-bright high;
    KB_STATE=3;
fi

echo "$KB_STATE" > "$STATE_FILE"
