#!/bin/bash

get_pwr() {
    PWR=$(asusctl profile -p | sed -n 's/Active profile is //p')
}

get_pwr

if [ $PWR == Balanced ]; then
    text="󰾅"
    tooltip="Balanced"
elif [ $PWR == Performance ]; then
    text="󰓅"
    tooltip="Performance"
elif [ $PWR == Quiet ]; then
    text="󰾆"
    tooltip="Quiet"
fi

echo '{"text": "'$text'", "tooltip": "'$tooltip'"}'

if [[ "$1" == "next" ]]; then
    asusctl profile -n;
    get_pwr
fi
